version: "3"
services:
    pg_master:
        build: ./db/master
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=00
            - POSTGRES_DB=dinein-recommender
            - PG_REP_USER=rep_postgres
            - PG_REP_PASSWORD=00
        ports:
            - "5432:5432"
        networks:
            default:
                aliases:
                    - db_cluster
    pg_slave:
        build: ./db/slave
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=00
            - POSTGRES_DB=dinein-recommender
            - PG_REP_USER=rep_postgres
            - PG_REP_PASSWORD=00
            - PG_MASTER_HOST=pg_master
        ports:
            - "5433:5432"
        depends_on:
            - pg_master
        networks:
            default:
                aliases:
                    - db_cluster
    adminer:
        container_name: "adminer"
        image: adminer:latest
        restart: always
        ports:
            - 8888:8080

    # api:
    #     container_name: api
    #     build: ./
    #     restart: always
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - pg_master
    #         - pg_slave
    #     networks:
    #         default:
    #             aliases:
    #                 - db_cluster

volumes:
    db_data:

