@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzk5NDYwODMsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2Nzk5ODkyODN9.N_A0BBHIlGNQbsbdFm25qH3PElykEswaaRVgVywufH8IXDnbLWnlHgVcN44x-h7CPZbvaw6JztLTQJhE7geJAJL0xI2Nhsm45TT9wohgmzgcMIbgPsD4J7_VargNbJ6pJyUPpi-9fffPfLHvfOMK3GNtIVCZvz2ptvLvhoATJVoTRAUvgBTd3RQzmCVWbvDpHw4nC3EON53kcz8DlMbs-GC6Z_z6lPiqbp8ssjDBIkeApjanjiLPHlpYHr1JmLlHd_vJIm785hg4EXzCF0ZVor5msFtCuivpYPzHoyNxwOTRr5EOH9cH3LGs5s1xIfTCrcOsfslXoTc86NjAk2-AppbJ4wGnx9auQ29I7fT9t1o9jfarh_F4C9Taz7YC63k5uaMOtecMkiZfMDwWnXqkVtiMOVXA7Vya6iX59S1v0K3IYZv9HMzE4zV9DxpW_663nrcjiJCb-RVE9WMSWmSnKigXRZ5gTicHaiTjlEzLjUWT7iC6bMX6eG7Ydl_Zm74JKXdylXRZW5Uz_GgnM0n2s3Sg1LxMgvI1qlXltuIziDpVM2oaCqANJpwiL9ayq7UN2pGUFhxMXG6VwEMQNAumfJuD1eRcOh1mAaQBzOfeQp_QWiqoEZgb-wJ2k8gNyQ333mWSL-xjPp24GTaUcUQFXu0Vdq4buQi9tBDaI07DVxs
@api = http://localhost:8000/api

### get recommended restaurants
GET {{api}}/dinein/recommend/U1001
Authorization: Bearer {{token}}
### register a rating
POST {{api}}/dinein/rating/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userID": "U1138",
    "placeID":"132001",
    "food_rating": 3.2,
    "service_rating": 5
}

### eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzk4Njg2ODgsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2Nzk5MTE4ODh9.hrf6RMELN-OWVwtaDB0bW3Zg494ZJBPgk8aYm9wjJmDVKlOXDLY6YD1GCxplxTYrIzij9mkuzUWTWuURwPLr4FlMPp_wU0wDuGcQeQUCzpNbOjJmInIhtFbcACRXGaS8joftIc0p8SKB_NftOHlSCIYyNA2Ct74BNMoOsKLBfN6xuyaeLaH_tV6dyLcjC0bE-UESqDV6Ch_KYS5dfJR9YpUygJ_Z-JOrr-K1UpX64GofJoMssRT7wjbpoBWpxtgp6KzfFWVp3V0MbA2fFx51GbrgrLq-9u9XrRrhGdFmMFvHOwVgL9R-GwHeiBBeyIysTgIwlpuYN-5Nf77zID5D1pfGjI_NA4L8eT44Y4AZZnBI10redJW9Zs8Wgp9PkwxwlUE80CF2iF-1hiGIWPQlq-1LegQc3-8yVJnT_SpVZaZYIbFHHRLtQ_odQehHmH0XO0DauTvTySUMUoAajLiRQatKz3sBnrY1aTCbNLEcJlazkFsduTUIH1YVifJg9xsIoltMonLlcow_f_x8RUgXohxiVDRvKFhsEgsr6RNlCCh30XM6WxzfWYKYKQNq3fu9Z4PRBDTIKEFQD0v7BKvhdr2IOBXzG8u-Jgw7uTOzTlIqtG2F4h18ww6CWEDoa-bmdXu8D3fwajMrnOu3RPibC0OqW4YHxOCPG6ox2RTWxFE

