@token =eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA1OTE3MDQsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2ODA2MzQ5MDR9.1xznM5YlnmqbnReSnBvGwCBLVL9ws3Ua42dvNm0rdglP49bIzLPgHyVTjFFGkGzN8i7LcSGaIBXhnopNJILVKn4pNv04Kal1GXAULzQBcplUiCJ9sFGU0q70zYnqVmGZGNAVM8DDZziGs3f_dqexWB5lizXovU2BiBt1w-x5iR253Odo6kMfiicYUlHnAUPonJYHcLXQn6jYAZPj6HkdqO7O-jMPnBwfcUAoE-0xuBRr-5Mff0RQvV7frBWiFOuInidPUzRo94kC23L7kx-p0FctcyjvubTL8gA8rKY51zzFZdFJ2DJFnzmBROyh3dUcsLN4NRksrZKEdIUW04HDCO_Lv8MMGT_yrjWjgv8WHof8hQ9d6GZ_6pJA2N5g9alllenAZneQ1C8vMR66ihGHTejdcwFAIZTc189ofrJKAwLyofMYqAa9UmUbZbjAh5vhV8tsK3nycG9o3TjtYMd8dUxQCD9MuO3GDpWcuUCMumBvpAt0Oz5Hi2jArfvTjFstoT2_8Udu0UxTcAlBA_7A_Q1K9ZICblUNkMdaB0hVTDHPLh7z4LJxxgdLsXjuYqnIN_Tyz-VXPiUKXv7KmTyAf_jQxDP2PGnu0ikuPlRcd3go9ZlCeuI-kWEC7_sjJBykKGulfC5H0beIxnPwrAJuIs7sgExlwS5YDsfx8lpBO18
@api = http://localhost:8000/api

### get recommended restaurants
GET {{api}}/dinein/recommend/U1141
Authorization: Bearer {{token}}

### get most visited restaurants
GET {{api}}/dinein/most-visited/U1141
Authorization: Bearer {{token}}

### register a rating
POST {{api}}/dinein/rating/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userID": "U1001",
    "placeID":"132001",
    "food_rating": 3.2,
    "service_rating": 5
}

# "userID": "U1138",
### eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzk4Njg2ODgsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2Nzk5MTE4ODh9.hrf6RMELN-OWVwtaDB0bW3Zg494ZJBPgk8aYm9wjJmDVKlOXDLY6YD1GCxplxTYrIzij9mkuzUWTWuURwPLr4FlMPp_wU0wDuGcQeQUCzpNbOjJmInIhtFbcACRXGaS8joftIc0p8SKB_NftOHlSCIYyNA2Ct74BNMoOsKLBfN6xuyaeLaH_tV6dyLcjC0bE-UESqDV6Ch_KYS5dfJR9YpUygJ_Z-JOrr-K1UpX64GofJoMssRT7wjbpoBWpxtgp6KzfFWVp3V0MbA2fFx51GbrgrLq-9u9XrRrhGdFmMFvHOwVgL9R-GwHeiBBeyIysTgIwlpuYN-5Nf77zID5D1pfGjI_NA4L8eT44Y4AZZnBI10redJW9Zs8Wgp9PkwxwlUE80CF2iF-1hiGIWPQlq-1LegQc3-8yVJnT_SpVZaZYIbFHHRLtQ_odQehHmH0XO0DauTvTySUMUoAajLiRQatKz3sBnrY1aTCbNLEcJlazkFsduTUIH1YVifJg9xsIoltMonLlcow_f_x8RUgXohxiVDRvKFhsEgsr6RNlCCh30XM6WxzfWYKYKQNq3fu9Z4PRBDTIKEFQD0v7BKvhdr2IOBXzG8u-Jgw7uTOzTlIqtG2F4h18ww6CWEDoa-bmdXu8D3fwajMrnOu3RPibC0OqW4YHxOCPG6ox2RTWxFE


### register a rating
GET {{api}}/dinein/get-data
Content-Type: application/json
Authorization: Bearer {{token}}
