@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA1OTE3MDQsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2ODA2MzQ5MDR9.1xznM5YlnmqbnReSnBvGwCBLVL9ws3Ua42dvNm0rdglP49bIzLPgHyVTjFFGkGzN8i7LcSGaIBXhnopNJILVKn4pNv04Kal1GXAULzQBcplUiCJ9sFGU0q70zYnqVmGZGNAVM8DDZziGs3f_dqexWB5lizXovU2BiBt1w-x5iR253Odo6kMfiicYUlHnAUPonJYHcLXQn6jYAZPj6HkdqO7O-jMPnBwfcUAoE-0xuBRr-5Mff0RQvV7frBWiFOuInidPUzRo94kC23L7kx-p0FctcyjvubTL8gA8rKY51zzFZdFJ2DJFnzmBROyh3dUcsLN4NRksrZKEdIUW04HDCO_Lv8MMGT_yrjWjgv8WHof8hQ9d6GZ_6pJA2N5g9alllenAZneQ1C8vMR66ihGHTejdcwFAIZTc189ofrJKAwLyofMYqAa9UmUbZbjAh5vhV8tsK3nycG9o3TjtYMd8dUxQCD9MuO3GDpWcuUCMumBvpAt0Oz5Hi2jArfvTjFstoT2_8Udu0UxTcAlBA_7A_Q1K9ZICblUNkMdaB0hVTDHPLh7z4LJxxgdLsXjuYqnIN_Tyz-VXPiUKXv7KmTyAf_jQxDP2PGnu0ikuPlRcd3go9ZlCeuI-kWEC7_sjJBykKGulfC5H0beIxnPwrAJuIs7sgExlwS5YDsfx8lpBO18
@api = http://localhost:8000/api

### register a new user
POST {{api}}/users/signup
Content-Type: application/json

{
    "username": "sertdfs2",
    "email": "ao12.doereer@gmail.com",
    "password":"Denis@600",
    "phone_number":"89098765467"
}

### login a user
POST {{api}}/users/login
Content-Type: application/json

{
    "idenfitier":"user1001",
    "password":"user1001"
}


### return all the users with default limit of 10
GET {{api}}/users
Authorization: Bearer {{ token }}

#####
# provide page and limit to get the users in the page or default page is 1 and limit is 10
GET {{api}}/users?page=1&limit=1
Authorization: Bearer {{ token }}


### if q is provided then it will return the users with the name containing the q || the email containing the q || the phone number containing the q
GET {{api}}/users?q=To s
Authorization: Bearer {{ token }}

### filter by date
GET {{api}}/users?filter[startDate]=2020-01-01&filter[endDate]=2022-04-31
Authorization: Bearer {{ token }}

### search by id
GET {{api}}/users/1028044654
Authorization: Bearer {{ token }}


###
PUT {{api}}/users/1028044654
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "phone_number": 7878787,
    "designetion": "Crew"
}

### 
PATCH {{api}}/users/1028044654
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "oldPassword":"Denis@600",
    "newPassword": "Denis@700",
    "email":"ao.doerer@gmail.com"
}


###
DELETE {{api}}/users/6
Authorization: Bearer {{ token }}
