@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA0MjIxOTUsInN1YiI6MSwidXNlcklEIjoiVTEwMDEiLCJleHAiOjE2ODA0NjUzOTV9.ZlSMc7Zdf2ZUI6fxyQkS6s5QVfLp_S6YVzxEpfqaVI9Z95jX9iORa0WzGugIb8GZtlvOIn-nDa0FROfd1bRqQ8O6V6my91TwtnZoLjnASb2YEmuYZy09jVsN06inlmlvnl19EWI4HGT4i1J6tcwcgP1Mj0Uo1AQmVjgfOCICgnosatVwgc7cxowIn4NGAS1oQJIs3nJE-4M7rBbA0ysLphRS6Qh5nvXJCPsfqU9uQq2YRxbeKCRyF67XBCt2k3Iqjspy0viMxEDtO9Ae7ZP8pYtWwfZd-ooGClcmlFIfuradaIMg07dOFYR_IBgwjB577-Nf8su1jKV-dzqLGw6jK5dCNPjeST6_h_Fl6agWehjuSPA61eebrrOo9WFXO-u8A6TgcL9N6TODVT3IUf8lHJOuXfGt0VlK2kmBvH_txA8yoUnEPQSp0A1bLBuVUMXoTfETyC175SyyQ6W0ab5s4iOQzfO4tpAgI7wR64oSZpTFLcvpSqY_i8RTlxoCwpE2k7xjatqZedOeuG1LQVHu8dZduICuAMvU0U1BjodyQOvSpI_QX298-Zp-MZisOjMCjoewd7kyH_V7zwUD1PReTQNvV73xomV6aD3U2r-pZrMuS8x5P5PpEpvk9SsMNku2-g74ZhXrDwaaKlMWJ26dNSsfMdosKRAmgKtr1Co4_mA
@api = http://localhost:8000/api

### register a new user
POST {{api}}/users/signup
Content-Type: application/json

{
    "username": "sertdfs",
    "email": "ao.doereer@gmail.com",
    "password":"Denis@600",
    "phone_number":"01242505250"
}

### login a user
POST {{api}}/users/login
Content-Type: application/json

{
    "idenfitier":"user1001",
    "password":"user1001"
}


### return all the users with default limit of 10
GET {{api}}/users
Authorization: Bearer {{ token }}

#####
# provide page and limit to get the users in the page or default page is 1 and limit is 10
GET {{api}}/users?page=1&limit=1
Authorization: Bearer {{ token }}


### if q is provided then it will return the users with the name containing the q || the email containing the q || the phone number containing the q
GET {{api}}/users?q=To s
Authorization: Bearer {{ token }}

### filter by date
GET {{api}}/users?filter[startDate]=2020-01-01&filter[endDate]=2022-04-31
Authorization: Bearer {{ token }}

### search by id
GET {{api}}/users/1028044654
Authorization: Bearer {{ token }}


###
PUT {{api}}/users/1028044654
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "phone_number": 7878787,
    "designetion": "Crew"
}

### 
PATCH {{api}}/users/1028044654
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "oldPassword":"Denis@600",
    "newPassword": "Denis@700",
    "email":"ao.doerer@gmail.com"
}


###
DELETE {{api}}/users/6
Authorization: Bearer {{ token }}
